apiVersion: v1
kind: Secret
metadata:
  name: nlp-dialogue-secret
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres
  OPENAI_API_KEY: "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"
